# Generated by Django 4.1.2 on 2022-10-22 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name=" :اسم الشركة")),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="سعر الرحلة")),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="المعاد"
                    ),
                ),
                (
                    "kids",
                    models.CharField(max_length=250, verbose_name=" :سياسة الاطفال"),
                ),
                (
                    "days",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("السبت", "السبت"),
                            ("الاحد", "الاحد"),
                            ("الاثنين", "الاثنين"),
                            ("الثلاثاء", "الثلاثاء"),
                            ("الاربعاء", "الاربعاء"),
                            ("الخميس", "الخميس"),
                            ("الجمعه", "الجمعه"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "end",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="End",
                        to="flyin.airport",
                    ),
                ),
                (
                    "start",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Start",
                        to="flyin.airport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aircom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name=" :اسم الشركة")),
                ("logo", models.ImageField(upload_to="flyin/")),
                ("about", models.TextField(max_length=250, verbose_name=":عن الشركة")),
                (
                    "phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "secondPhoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
