# Generated by Django 4.1.2 on 2022-10-22 23:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name=" :اسم الشركة")),
                ("logo", models.ImageField(upload_to="day-use/company")),
                ("about", models.TextField(max_length=250, verbose_name=":عن الشركة")),
                (
                    "phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "secondPhoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dest", models.CharField(max_length=40)),
                ("img", models.ImageField(upload_to="day-use/destination")),
            ],
        ),
        migrations.CreateModel(
            name="fromwhere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fromm", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pic", models.ImageField(upload_to="day-use/day")),
                ("price", models.IntegerField(default=0, verbose_name="سعر الرحلة")),
                (
                    "date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="المعاد"
                    ),
                ),
                ("program", models.TextField(verbose_name="البرنامج")),
                (
                    "comm",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oneday.company",
                    ),
                ),
                (
                    "froom",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oneday.fromwhere",
                    ),
                ),
                (
                    "too",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="oneday.destination",
                    ),
                ),
            ],
        ),
    ]
