# Generated by Django 4.1.2 on 2022-10-22 23:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dest", models.CharField(max_length=40)),
                ("img", models.ImageField(upload_to="wedding/destination")),
            ],
        ),
        migrations.CreateModel(
            name="hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name=" :اسم القاعة")),
                ("imgs", models.ImageField(upload_to="wedding/hall")),
                ("about", models.TextField(max_length=250, verbose_name=":عن القاعة")),
                (
                    "phoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                (
                    "secondPhoneNumber",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="سعر القاعة")),
                ("number", models.IntegerField(default=0, verbose_name="عدد الافراد ")),
                (
                    "address",
                    models.CharField(max_length=50, verbose_name=" :اسم القاعة"),
                ),
                (
                    "optionss",
                    models.TextField(max_length=250, verbose_name=": الاضافات"),
                ),
                (
                    "program",
                    models.TextField(max_length=250, verbose_name=":برنامج الفرح "),
                ),
                (
                    "location",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wedding.destination",
                    ),
                ),
            ],
        ),
    ]
